export const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  "@id": "https://anton-belousov-cv.vercel.app/#person",
  name: "Anton Belousov",
  alternateName: [
    "Anton Belousov Senior Frontend Engineer",
    "Anton Belousov JavaScript Developer",
    "Anton Belousov React Developer",
  ],
  jobTitle: "Senior Frontend Engineer",
  image:
    "https://anton-belousov-cv.vercel.app/img/anton-belousov-senior-frontend-engineer.webp",
  email: "polpoltrop228@gmail.com",
  telephone: "+380663208556",
  address: {
    "@type": "PostalAddress",
    addressLocality: "Kyiv",
    addressCountry: "Ukraine",
  },
  url: "https://anton-belousov-cv.vercel.app",
  mainEntityOfPage: "https://anton-belousov-cv.vercel.app/",
  disambiguatingDescription:
    "Anton Belousov is a Senior JavaScript and Frontend Developer from Kyiv, Ukraine, focused on React, Next.js, TypeScript, technical SEO, Core Web Vitals, and frontend architecture.",
  sameAs: [
    "https://github.com/antonbelous0v",
    "https://www.linkedin.com/in/anton-belousov-1803042b1/",
    "https://anton-belousov-cv.vercel.app/blog",
  ],
  description:
    "Senior Frontend Engineer with 5+ years building scalable React/Next.js apps. Performance (Core Web Vitals 90+), technical SEO, WebGL/Three.js, FSD architecture. 40-60% load time reduction, 30-50% PageSpeed improvements. Leads frontend teams.",
  hasOccupation: {
    "@type": "Occupation",
    name: "Senior Frontend Engineer",
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Redux",
      "Redux Toolkit",
      "GraphQL",
      "Apollo Client",
      "Apollo Server",
      "Apollo Federation",
      "REST API",
      "Three.js",
      "WebGL",
      "GLSL",
      "Shaders",
      "Service Worker",
      "Web Worker",
      "FSD",
      "Core Web Vitals",
      "Lighthouse",
      "PageSpeed Insights",
      "Technical SEO",
      "JavaScript Performance Optimization",
      "Adaptive Layouts",
      "Schema.org",
      "Webpack",
      "Vite",
      "Git",
      "CI/CD",
      "GitHub Actions",
      "Vercel",
      "Jest",
      "React Testing Library",
    ],
    responsibilities:
      "Development of high-performance web applications, technical SEO optimization, WebGL/Three.js interfaces, code refactoring and performance improvements.",
  },
  workLocation: {
    "@type": "Place",
    address: {
      "@type": "PostalAddress",
      addressLocality: "Kyiv",
      addressCountry: "Ukraine",
    },
  },
  alumniOf: {
    "@type": "EducationalOrganization",
    name: "Kyiv European University",
  },
  knowsAbout: [
    "React",
    "React Developer",
    "Next.js",
    "Next.js Developer",
    "TypeScript",
    "TypeScript Developer",
    "JavaScript",
    "Senior JavaScript Developer",
    "Senior Frontend Developer",
    "Redux",
    "GraphQL",
    "Apollo Client",
    "Apollo Server",
    "Apollo Federation",
    "REST API",
    "Three.js",
    "WebGL",
    "GLSL",
    "Shaders",
    "Service Worker",
    "Web Worker",
    "FSD",
    "Core Web Vitals",
    "Technical SEO",
    "JavaScript Performance Optimization",
    "Adaptive Layouts",
    "System Design",
    "Frontend Architecture",
    "Team Leadership",
    "Mentoring",
    "Code Refactoring",
    "Webpack",
    "Vite",
    "Git",
    "CI/CD",
    "Jest",
    "Anton Belousov",
    "Senior Frontend Engineer",
    "Ukraine",
  ],
  knowsLanguage: [
    {
      "@type": "Language",
      name: "English",
      proficiencyLevel: "B1/B2",
    },
    {
      "@type": "Language",
      name: "Ukrainian",
      proficiencyLevel: "Native",
    },
  ],
};
